comments and minor changes to code

diff --git a/New-User-Script/NewUser-script b/New-User-Script/NewUser-script
--- a/New-User-Script/NewUser-script
+++ b/New-User-Script/NewUser-script
@@ -6,9 +6,9 @@
 # copy contents of /etc/skel into home directory
 # create user new password using passwd
 
-
+# dosent need to creat just add
 #Do i need to make new groups that they specify or add them to specified groups?
-#how robust is the error handling supposed tobe
+#how robust is the error handling supposed tobe 
 #are we supposed to include instructions in the scripts or on readme
 
 
@@ -32,27 +32,32 @@ while getopts ":u:g:s:" opt; do
 		;;
 
 	s)
-		echo "i"
 		specifiedshell=${OPTARG}
 		echo "$specifiedshell"
 		;;
 		
 	:)
-		echo "Error: requires an argument"
+		echo "Error:this flag requires an argument"
+		exit 1
+		;;
+	?)
+		echo "Error: this option does not exist"
 		exit 1
 		;;
 	esac
 done
 
 if [[ -n $name && -n $specifiedshell ]]; then
-	# mkdir -p /home/$name
-	# echo "$name:x:$newUid:$newGuid:/home/$name:/bin/$specifiedshell" >> /etc/passwd
-	# echo "$name:x:$newGuid:" >> /etc/group
-	# cp -a /etc/skel/. /home/$name
-	# chown $name:$name /home/$name
+	mkdir -p /home/$name
+	echo "$name:x:$newUid:$newGuid:/home/$name:/bin/$specifiedshell" >> /etc/passwd
+	echo "$name:x:$newGuid:" >> /etc/group
+	cp -r /etc/skel/. /home/$name
+	chown $name:$name /home/$name
+	passwd "$name"
+fi
 #	for i in ${groups[@]}; do
 #		echo "$i"
-fi
+#fi
 	
 
 
